(require 'deft)
(setq deft-directory "~/Dropbox/notes")
(setq deft-extensions '("org" "md" "txt"))
(setq deft-default-extension "org")
(setq deft-use-filename-as-title t)
(setq deft-use-filter-string-for-filename t)
(setq deft-auto-save-interval 0)
(setq org-src-fontify-natively t)
;;(global-set-key [f7] 'deft)
(global-set-key (kbd "C-x d") 'deft)
(global-set-key (kbd "C-x g") 'deft-find-file)
(provide 'init-deft)
