#!/usr/bin/env bash

# Easier navigation: .., ..., ...., ....., ~ and -
alias ..="cd .."
alias ...="cd ../.."
alias ~="cd ~" # `cd` is probably faster to type though
alias -- -="cd -"

# Always enable colored `grep` output
# Note: `GREP_OPTIONS="--color=auto"` is deprecated, hence the alias usage.
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# IP addresses
#alias mip="dig +short myip.opendns.com @resolver1.opendns.com"
alias mip="curl http://ip.cn/"

# URL-encode strings
alias urlencode='python -c "import sys, urllib as ul; print ul.quote_plus(sys.argv[1]);"'

# Print each PATH entry on a separate line
alias path='echo -e ${PATH//:/\\n}'

# Python Web Server
alias sw='python -m SimpleHTTPServer $1'

# Pandoc
alias pandoc='pandoc -s -S --latex-engine=xelatex -V mainfont="WenQuanYi Micro Hei Mono"'

# Costom
alias df='df -h'
alias du='du -sh'
alias p="cd ~/GlobalProject"
alias sr="sudo su -"
alias k="cat $HOME/nut/notes/keymap.txt"

# SSH 
alias rdo='ssh root@rdo'
alias eayun='ssh root@eayunstack'
alias obs='ssh root@obs'
alias remote='ssh root@192.168.2.64'
alias node-8='ssh root@25.0.0.5'
alias 45='ssh root@192.168.2.45'
alias 92='ssh root@192.168.2.147'
alias cephdev='ssh root@192.168.6.142'
