#!/usr/bin/env bash

# Easier navigation: .., ..., ...., ....., ~ and -
alias ..="cd .."
alias ...="cd ../.."
alias ~="cd ~" # `cd` is probably faster to type though
alias -- -="cd -"

# Always enable colored `grep` output
# Note: `GREP_OPTIONS="--color=auto"` is deprecated, hence the alias usage.
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# IP addresses
#alias mip="dig +short myip.opendns.com @resolver1.opendns.com"
alias mip="curl ifconfig.me"

# URL-encode strings
alias urlencode='python -c "import sys, urllib as ul; print ul.quote_plus(sys.argv[1]);"'

# Print each PATH entry on a separate line
alias path='echo -e ${PATH//:/\\n}'

# Python Web Server
alias sw='python -m SimpleHTTPServer $1'

# Pandoc
#alias pandoc='pandoc -s -S --latex-engine=xelatex -V mainfont="WenQuanYi Micro Hei Mono"'
#alias pandoc='pandoc -V mainfont="WenQuanYi Micro Hei Mono"'

# Costom
alias df='df -h'
alias du='du -sh'
alias p="cd ~/GlobalProject"
alias sr="sudo su -"

# SSH 

# fuck
# eval $(thefuck --alias)

# docker
alias doc="docker"

# cp
alias rcp="rsync -avzP --progress --stats"

# axel
alias axel="axel -n 10 -a -S5"

#alias for cnpm
alias cnpm="npm --registry=https://registry.npm.taobao.org \
  --cache=$HOME/.npm/.cache/cnpm \
  --disturl=https://npm.taobao.org/dist \
  --userconfig=$HOME/.cnpmrc"
